services:
  backend:
    image: ${BACK_IMAGE:-373317459179.dkr.ecr.ap-northeast-2.amazonaws.com/web/backend:latest}
    # 또는 위에서 Dockerfile로 빌드 배포한다면: build: . 로 바꿔도 됨
    container_name: teacher-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
      # DB/Milvus 환경변수 필요시 추가
    # milvus, db를 같은 호스트에서 컨테이너로 쓴다면 depends_on 추가
